### ISSUE TITLE
ch-run-oci -v errors out

### ISSUE THREAD

**Issue by naterini** [hpc/charliecloud#1112]
I get this error requesting the version:

```
$ ch-run-oci -v
verbose level: 1
host architecture from uname: x86_64
host architecture for registry: amd64
Traceback (most recent call last):
  File "/usr/local/bin/ch-run-oci", line 315, in <module>
    main()
  File "/usr/local/bin/ch-run-oci", line 33, in main
    args = args_parse()
  File "/usr/local/bin/ch-run-oci", line 92, in args_parse
    bundle_ = bundle_from_cid(args_.cid)
AttributeError: 'Namespace' object has no attribute 'cid'
```

**Comment by reidpr** [comment]
`-v` is verbose. `--version` is for version:

```
$ ch-run-oci --version
0.24
```

Does that help?

**Comment by naterini** [comment]
Patching out the PEBCAK now.

**Comment by reidpr** [comment]
Happens to all of us!
