### ISSUE TITLE
ch-image: build: assertion error when no context directory is provided

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1372]
If you forget to pass context you get an assertion. This was previously an error message.
```
$ ch-image build -t snap -f ./Dockerfile.snap
Traceback (most recent call last):
  File "/home/jogas/git/charliecloud/bin/ch-image", line 280, in <module>
    main()
  File "/home/jogas/git/charliecloud/bin/ch-image", line 265, in main
    cli = ap.parse_args()
  File "/home/jogas/git/charliecloud/bin/../lib/charliecloud/charliecloud.py", line 315, in parse_args
    cli = super().parse_args(*args, **kwargs)
  File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 2001, in _parse_known_args
    ', '.join(required_actions))
  File "/usr/lib64/python3.6/argparse.py", line 2391, in error
    self.print_usage(_sys.stderr)
  File "/usr/lib64/python3.6/argparse.py", line 2361, in print_usage
    self._print_message(self.format_usage(), file)
  File "/usr/lib64/python3.6/argparse.py", line 2327, in format_usage
    return formatter.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib64/python3.6/argparse.py", line 337, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

**Comment by reidpr** [comment]
Can also reproduce with simply:

```
$ ch-image build
Traceback (most recent call last):
[...]
  File "/usr/lib/python3.9/argparse.py", line 350, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

It seems to have something to do with the `bucache` mutually exclusive group and `argparse` bugs when wrapping the usage string. Note the extra space after “[-h]”:

```
$ COLUMNS=1000 ch-image build
usage: ch-image build [-h]  [-b SRC[:DST]] [--build-arg ARG[=VAL]] [-f DOCKERFILE] [--force] [-n] [--no-force-detect] [--parse-only] [-t TAG] CONTEXT
ch-image build: error: the following arguments are required: CONTEXT
```

The `AssertionError` is `argparse` validating that said extra space is not present.

This particular error comes up a lot on Google.
