### ISSUE TITLE
`ch-image`: set storage function doesn't work

### ISSUE THREAD

**Issue by rstyd** [hpc/charliecloud#1691]
When trying to use the `--storage` option with `ch-image` I get this error:

```
ch-image --storage storage/
Traceback (most recent call last):
  File "/usr/projects/hpcsoft/toss3/common/x86_64/charliecloud/0.32/bin/ch-image", line 312, in <module>
    main()
  File "/usr/projects/hpcsoft/toss3/common/x86_64/charliecloud/0.32/bin/ch-image", line 295, in main
    ch.init(cli)
  File "/usr/projects/hpcsoft/toss3/common/x86_64/charliecloud/0.32/bin/../lib/charliecloud/charliecloud.py", line 632, in init
    if (cli.func.__module__ == "push"):
AttributeError: 'Namespace' object has no attribute 'func'
```

Notably this occurs on `0.32` and `0.33`.

**Comment by reidpr** [comment]
Note this is indeed a usage error but we should give a proper error message instead of crashing.
