### ISSUE TITLE
charliecloud v0.35 cannot pull [some images] correctly

### ISSUE THREAD

**Issue by MFTabriz** [hpc/charliecloud#1805]
When pulling containers using the latest version of charliecloud [v0.35] (on almalinux 8.6 with python 3.6) I get following error:

```
> ch-image pull XXXX

initializing storage directory: v7 XXXX/image
initializing empty build cache
pulling image: XXXX
requesting arch: amd64
manifest list: downloading: 100%
warning: image is architecture-unaware
warning: requested arch is amd64; using --arch=yolo
config: downloading: 100%
layer X/XX: xxxxxxx: downloading: 100%
...
pulled image: adding to build cache
flattening image
layer X/XX: xxxxxxx: listing
...
validating tarball members
warning: layer X/XX: xxxxxxx: skipping member with empty path
...
layer X/XX: xxxxxxx: changed 42 absolute symbolic and/or hard links to relative
Traceback (most recent call last):
File "/charliecloud/bin/ch-image", line 332, in <module>
main()
File "/charliecloud/bin/ch-image", line 323, in main
cli.func(cli)
File "/charliecloud/lib/charliecloud/pull.py", line 36, in main
bu.cache.pull_eager(dst_img, src_ref, cli.last_layer)
File "/charliecloud/lib/charliecloud/build_cache.py", line 1060, in pull_eager
self.pull_lazy(img, src_ref, last_layer, pullet)
File "/charliecloud/lib/charliecloud/build_cache.py", line 1072, in pull_lazy
pullet.unpack(last_layer)
File "/charliecloud/lib/charliecloud/pull.py", line 314, in unpack
self.image.unpack(layer_paths, last_layer)
File "/charliecloud/lib/charliecloud/image.py", line 464, in unpack
self.unpack_layers(layer_tars, last_layer)
File "/charliecloud/lib/charliecloud/image.py", line 524, in unpack_layers
self.validate_members(layers)
File "/charliecloud/lib/charliecloud/image.py", line 592, in validate_members
link_fix_ct += fs.TarFile.fix_link_target(m, fp.name)
File "/charliecloud/lib/charliecloud/filesystem.py", line 979, in fix_link_target
new = tgt.relative_to("/")
File "/charliecloud/lib/charliecloud/filesystem.py", line 515, in relative_to
ret.trailing_slash_p = other.trailing_slash_p
AttributeError: 'str' object has no attribute 'trailing_slash_p'
```

The issue does not happen using earlier versions. 

The relevant code has been added in 6dba8f0d5d357f52d234cb1bd4e15ac4ca78a795 and removed in aec9ba0d3470bc0f92f19b0eef706bdafb5ee65c

I’m opening this issue to help the others who will encounter it.

**Comment by reidpr** [comment]
Thank you @MFTabriz. Linking in PR #1708 and PR #1745 (neither of which have a parent issue) for reference.
