### ISSUE TITLE
ch-grow: needs better error handling for OSError

### ISSUE THREAD

**Issue by trandles-lanl** [hpc/charliecloud#815]
I generated a traceback today when trying to build a container image and the filesystem filled up. I managed to figure it out, but a friendlier error message would be nice.

```
[tim@malkovich build]$ ch-build -b ch-grow -t clamr-centos -f Dockerfile.clamr .
building with: ch-grow
growing: clamr-centos
  1 FROM malkovich:5050/tim/baseimages/centos-buildclamr:7 
manifest: downloading
layer 1/1: 6e77427: downloading
layer 1/1: 6e77427: listing
validating tarball members
resolving whiteouts
flattening image
layer 1/1: 6e77427: extracting
Traceback (most recent call last):
  File "/usr/local/charliecloud/0.17/bin/ch-grow", line 659, in <module>
    main()
  File "/usr/local/charliecloud/0.17/bin/ch-grow", line 191, in main
    ml.visit_topdown(tree)
  File "/usr/local/charliecloud/python3-env/3.6.8/lib/python3.6/site-packages/lark/visitors.py", line 225, 
    self._call_userfunc(subtree)
  File "/usr/local/charliecloud/python3-env/3.6.8/lib/python3.6/site-packages/lark/visitors.py", line 201, 
    return getattr(self, tree.data, self.__default__)(tree)
  File "/usr/local/charliecloud/0.17/bin/ch-grow", line 222, in __default__
    inst.execute()
  File "/usr/local/charliecloud/0.17/bin/ch-grow", line 256, in execute
    self.execute_()
  File "/usr/local/charliecloud/0.17/bin/ch-grow", line 506, in execute_
    image.copy_unpacked(self.base_image)
  File "/usr/local/charliecloud/0.17/bin/../lib/charliecloud/charliecloud.py", line 216, in copy_unpacked
    shutil.copytree(other.unpack_path, self.unpack_path, symlinks=True)
  File "/usr/local/charliecloud/python3-env/3.6.8/lib64/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/var/tmp/tim/ch-grow/img/malkovich:5050%tim%baseimages%centos-buildclamr:7/usr/lib64/python3.6/__pycache__/sre_co/
[tim@malkovich build]$ df -h /var/tmp
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2.0G  2.0G     0 100% /var/tmp

**Comment by reidpr** [comment]
I'll try to reproduce this using `alpine:3.9`, which has a tarball of 2.7MiB and unpacked directory of 5.5 MiB.

**Comment by reidpr** [comment]
Case 1: `ENOSPC` during unpacking. Crashes, but clear error message.

```
$ sudo mount -o size=4M -t tmpfs tmpfs /var/tmp/reidpr/ch-grow
$ df -h /var/tmp/reidpr/ch-grow
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           4.0M     0  4.0M   0% /var/tmp/reidpr/ch-grow
$ ch-tug alpine:3.9
pulling image:   alpine:3.9
destination:     /var/tmp/reidpr/ch-grow/img/alpine:3.9

manifest: downloading
layer 1/1: 3160359: downloading
layer 1/1: 3160359: listing
validating tarball members
resolving whiteouts
flattening image
layer 1/1: 3160359: extracting
Traceback (most recent call last):
  File "/home/reidpr/charliecloud/bin/ch-tug", line 72, in <module>
    main()
  File "/home/reidpr/charliecloud/bin/ch-tug", line 65, in main
    image.pull_to_unpacked(use_cache=(not args.no_cache))
  File "/home/reidpr/charliecloud/bin/../lib/charliecloud/charliecloud.py", line 339, in pull_to_unpacked
    self.flatten()
  File "/home/reidpr/charliecloud/bin/../lib/charliecloud/charliecloud.py", line 281, in flatten
    fp.extractall(path=self.unpack_path, members=members)
  File "/usr/lib/python3.7/tarfile.py", line 2004, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2046, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2116, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2165, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.7/tarfile.py", line 250, in copyfileobj
    dst.write(buf)
OSError: [Errno 28] No space left on device
$ sudo umount /var/tmp/reidpr/ch-grow
```

**Comment by reidpr** [comment]
Case 2: `ENOSPC` during download. Fails with error. Leaves broken tarball behind, which may break later re-tries because we don't validate checksums. I think this is more or less OK for now; I'm not sure how to decide whether to delete the files after a failed download.

```
$ sudo mount -o size=2M -t tmpfs tmpfs /var/tmp/reidpr/ch-grow
$ ch-tug alpine:3.9
pulling image:   alpine:3.9
destination:     /var/tmp/reidpr/ch-grow/img/alpine:3.9

manifest: downloading
layer 1/1: 3160359: downloading
error: can't write: /var/tmp/reidpr/ch-grow/dlcache/31603596830fc7e56753139f9c2c6bd3759e48a850659506ebfb885d1cf3aef5.tar.gz: [Errno 28] No space left on device
$ ls /var/tmp/reidpr/ch-grow/dlcache/
31603596830fc7e56753139f9c2c6bd3759e48a850659506ebfb885d1cf3aef5.tar.gz
alpine:3.9.manifest.json
$ sudo umount /var/tmp/reidpr/ch-grow
```

**Comment by reidpr** [comment]
Case 3: Dockerfile: `ENOSPC` during copy of base image (i.e., `FROM` instruction). Reproduces the above. We get a backtrace listing dozens or hundreds of files; I think this may be every single file that failed, and we did not stop trying to copy after the first file.

```
$ sudo mount -o size=10M -t tmpfs tmpfs /var/tmp/reidpr/ch-grow
$ printf 'FROM alpine:3.9\n' | ch-grow -t foo -f - /tmp
growing: foo
  1 FROM alpine:3.9
manifest: downloading
layer 1/1: 3160359: downloading
layer 1/1: 3160359: listing
validating tarball members
resolving whiteouts
flattening image
layer 1/1: 3160359: extracting
Traceback (most recent call last):
  File "/home/reidpr/charliecloud/bin/ch-grow", line 659, in <module>
    main()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 191, in main
    ml.visit_topdown(tree)
  File "/usr/local/lib/python3.7/dist-packages/lark/visitors.py", line 225, in visit_topdown
    self._call_userfunc(subtree)
  File "/usr/local/lib/python3.7/dist-packages/lark/visitors.py", line 201, in _call_userfunc
    return getattr(self, tree.data, self.__default__)(tree)
  File "/home/reidpr/charliecloud/bin/ch-grow", line 222, in __default__
    inst.execute()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 256, in execute
    self.execute_()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 506, in execute_
    image.copy_unpacked(self.base_image)
  File "/home/reidpr/charliecloud/bin/../lib/charliecloud/charliecloud.py", line 216, in copy_unpacked
    shutil.copytree(other.unpack_path, self.unpack_path, symlinks=True)
  File "/usr/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/var/tmp/reidpr/ch-grow/img/alpine:3.9/lib/libcrypto.so.1.1', '/var/tmp/reidpr/ch-grow/img/foo/lib/libcrypto.so.1.1', '[Errno 28] No space left on device'), ('/var/tmp/reidpr/ch-grow/img/alpine:3.9/lib/ld-musl-x86_64.so.1', '/var/tmp/reidpr/ch-grow/img/foo/lib/ld-musl-x86_64.so.1', '[Errno 28] No space left on device'), [... long list trimmed ...] ]
$ sudo umount /var/tmp/reidpr/ch-grow
```

**Comment by reidpr** [comment]
Case 4: Dockerfile: `ENOSPC` during build (here, `RUN` instruction). This one seems in good shape actually. The result probably depends on the command being `RUN`.

```
$ sudo mount -o size=20M -t tmpfs tmpfs /var/tmp/reidpr/ch-grow
$ printf 'FROM alpine:3.9\nRUN apk add vim\n' | ch-grow -t foo -f - /tmp
growing: foo
  1 FROM alpine:3.9
manifest: downloading
layer 1/1: 3160359: downloading
layer 1/1: 3160359: listing
validating tarball members
resolving whiteouts
flattening image
layer 1/1: 3160359: extracting
  2 RUN ['/bin/sh', '-c', 'apk add vim']
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/5) Installing lua5.3-libs (5.3.5-r2)
(2/5) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(3/5) Installing ncurses-terminfo (6.1_p20190105-r0)
(4/5) Installing ncurses-libs (6.1_p20190105-r0)
ERROR: Failed to create usr/lib/libncursesw.so.6.1: No space left on device
ERROR: ncurses-libs-6.1_p20190105-r0: No space left on device
(5/5) Installing vim (8.1.1365-r0)
ERROR: Failed to create usr/bin/vim: No space left on device
ERROR: vim-8.1.1365-r0: No space left on device
2 errors; 13 MiB in 17 packages
error: command failed with code 2: /home/reidpr/charliecloud/bin/ch-run
$ sudo umount /var/tmp/reidpr/ch-grow
```

**Comment by reidpr** [comment]
That said, probably each instruction needs to be examined, e.g. `COPY` large file.

**Comment by reidpr** [comment]
Case 4a: `COPY`. Fails with uncaught `OSError`.

```
$ sudo mount -o size=20M -t tmpfs tmpfs /var/tmp/reidpr/ch-grow
$ dd if=/dev/urandom of=/tmp/32M bs=1M count=32
32+0 records in
32+0 records out
33554432 bytes (34 MB, 32 MiB) copied, 0.0911608 s, 368 MB/s
(reverse-i-search)`ch-grow': bin/^C-grow --version
$ printf 'FROM alpine:3.9\nCOPY 32M .\n' | ch-grow -t foo -f - /tmp
growing: foo
  1 FROM alpine:3.9
manifest: downloading
layer 1/1: 3160359: downloading
layer 1/1: 3160359: listing
validating tarball members
resolving whiteouts
flattening image
layer 1/1: 3160359: extracting
  2 COPY ['32M'] -> '.'
Traceback (most recent call last):
  File "/home/reidpr/charliecloud/bin/ch-grow", line 659, in <module>
    main()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 191, in main
    ml.visit_topdown(tree)
  File "/usr/local/lib/python3.7/dist-packages/lark/visitors.py", line 225, in visit_topdown
    self._call_userfunc(subtree)
  File "/usr/local/lib/python3.7/dist-packages/lark/visitors.py", line 201, in _call_userfunc
    return getattr(self, tree.data, self.__default__)(tree)
  File "/home/reidpr/charliecloud/bin/ch-grow", line 222, in __default__
    inst.execute()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 256, in execute
    self.execute_()
  File "/home/reidpr/charliecloud/bin/ch-grow", line 411, in execute_
    shutil.copy2(src, dst, follow_symlinks=True)
  File "/usr/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device
$ sudo umount /var/tmp/reidpr/ch-grow
$ rm /tmp/32M
```

**Comment by reidpr** [comment]
I think the strategy is:

1. Wrap `shutil.copytree` to check for errors. This is a bit of a weird one because it raises a unique exception `shutil.Error` containing all the files that failed, and I don't see a way to tell it to just raise `OSError` the first time something goes wrong.
2. Audit the rest of the code for operations that can cause `OSError` and deal with those exceptions.

**Comment by reidpr** [comment]
I'm introducing a new function `charliecloud.ossafe` in another branch that may help.
